modLoader="javafml"
loaderVersion="[40,)"
license="Academic Free License v3.0"

[[mods]]
modId="dark_infection"
version="0.9.6"
displayName="The Dark Infection"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
logoFile="logo.png"
authors="quinn, MCreator, FiveNights2161"
description='''
Infect Everything!
'''

[[dependencies.dark_infection]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2]"
    ordering="NONE"
    side="BOTH"




