package net.mcreator.darkinfection.procedures;

import net.minecraftforge.fml.common.Mod;
import net.minecraftforge.eventbus.api.SubscribeEvent;
import net.minecraftforge.eventbus.api.Event;
import net.minecraftforge.event.world.WorldEvent;

import net.minecraft.world.level.block.Blocks;

import net.mcreator.darkinfection.network.DarkInfectionModVariables;
import net.mcreator.darkinfection.init.DarkInfectionModBlocks;

import javax.annotation.Nullable;

@Mod.EventBusSubscriber
public class InitVarsProcedure {
	@SubscribeEvent
	public static void onWorldLoad(WorldEvent.Load event) {
		execute(event);
	}

	public static void execute() {
		execute(null);
	}

	private static void execute(@Nullable Event event) {
		DarkInfectionModVariables.infectable_blocks.add(Blocks.STONE);
		DarkInfectionModVariables.infected_blocks.add(DarkInfectionModBlocks.VOIDSTONE.get());
		DarkInfectionModVariables.infectable_blocks.add(Blocks.DEEPSLATE);
		DarkInfectionModVariables.infected_blocks.add(DarkInfectionModBlocks.VOIDSTONE.get());
		DarkInfectionModVariables.infectable_blocks.add(Blocks.SAND);
		DarkInfectionModVariables.infected_blocks.add(DarkInfectionModBlocks.GRAVITYVOID.get());
		DarkInfectionModVariables.infectable_blocks.add(Blocks.GRAVEL);
		DarkInfectionModVariables.infected_blocks.add(DarkInfectionModBlocks.GRAVITYVOID.get());
		DarkInfectionModVariables.infectable_blocks.add(Blocks.DIRT);
		DarkInfectionModVariables.infected_blocks.add(DarkInfectionModBlocks.DARKDIRT.get());
		DarkInfectionModVariables.infectable_blocks.add(Blocks.GRASS_BLOCK);
		DarkInfectionModVariables.infected_blocks.add(DarkInfectionModBlocks.INFECTEDSOIL.get());
		DarkInfectionModVariables.infectable_blocks.add(Blocks.COBBLESTONE);
		DarkInfectionModVariables.infected_blocks.add(DarkInfectionModBlocks.VOID_COBBLE.get());
		DarkInfectionModVariables.infectable_blocks.add(Blocks.COBBLED_DEEPSLATE);
		DarkInfectionModVariables.infected_blocks.add(DarkInfectionModBlocks.VOID_COBBLE.get());
		DarkInfectionModVariables.infectable_blocks.add(Blocks.COAL_ORE);
		DarkInfectionModVariables.infected_blocks.add(DarkInfectionModBlocks.VOID_STONE_COAL_ORE.get());
		DarkInfectionModVariables.infectable_blocks.add(Blocks.DEEPSLATE_COAL_ORE);
		DarkInfectionModVariables.infected_blocks.add(DarkInfectionModBlocks.VOID_STONE_COAL_ORE.get());
		DarkInfectionModVariables.infectable_blocks.add(Blocks.IRON_ORE);
		DarkInfectionModVariables.infected_blocks.add(DarkInfectionModBlocks.VOID_STONE_IRON_ORE.get());
		DarkInfectionModVariables.infectable_blocks.add(Blocks.DEEPSLATE_IRON_ORE);
		DarkInfectionModVariables.infected_blocks.add(DarkInfectionModBlocks.VOID_STONE_IRON_ORE.get());
		DarkInfectionModVariables.infectable_blocks.add(Blocks.REDSTONE_ORE);
		DarkInfectionModVariables.infected_blocks.add(DarkInfectionModBlocks.VOID_STONE_REDSTONE_ORE.get());
		DarkInfectionModVariables.infectable_blocks.add(Blocks.DEEPSLATE_REDSTONE_ORE);
		DarkInfectionModVariables.infected_blocks.add(DarkInfectionModBlocks.VOID_STONE_REDSTONE_ORE.get());
		DarkInfectionModVariables.infectable_blocks.add(Blocks.REDSTONE_ORE);
		DarkInfectionModVariables.infected_blocks.add(DarkInfectionModBlocks.VOID_STONE_REDSTONE_ORE_LIT.get());
		DarkInfectionModVariables.infectable_blocks.add(Blocks.LAPIS_ORE);
		DarkInfectionModVariables.infected_blocks.add(DarkInfectionModBlocks.VOID_STONE_LAPIS_ORE.get());
		DarkInfectionModVariables.infectable_blocks.add(Blocks.DEEPSLATE_LAPIS_ORE);
		DarkInfectionModVariables.infected_blocks.add(DarkInfectionModBlocks.VOID_STONE_LAPIS_ORE.get());
		DarkInfectionModVariables.infectable_blocks.add(Blocks.EMERALD_ORE);
		DarkInfectionModVariables.infected_blocks.add(DarkInfectionModBlocks.VOID_STONE_EMERALD_ORE.get());
		DarkInfectionModVariables.infectable_blocks.add(Blocks.DEEPSLATE_EMERALD_ORE);
		DarkInfectionModVariables.infected_blocks.add(DarkInfectionModBlocks.VOID_STONE_EMERALD_ORE.get());
		DarkInfectionModVariables.infectable_blocks.add(Blocks.DIAMOND_ORE);
		DarkInfectionModVariables.infected_blocks.add(DarkInfectionModBlocks.VOID_STONE_DIAMOND_ORE.get());
		DarkInfectionModVariables.infectable_blocks.add(Blocks.DEEPSLATE_DIAMOND_ORE);
		DarkInfectionModVariables.infected_blocks.add(DarkInfectionModBlocks.VOID_STONE_DIAMOND_ORE.get());
		DarkInfectionModVariables.infectable_blocks.add(Blocks.COPPER_ORE);
		DarkInfectionModVariables.infected_blocks.add(DarkInfectionModBlocks.VOID_STONE_COPPER_ORE.get());
		DarkInfectionModVariables.infectable_blocks.add(Blocks.DEEPSLATE_COPPER_ORE);
		DarkInfectionModVariables.infected_blocks.add(DarkInfectionModBlocks.VOID_STONE_COPPER_ORE.get());
		DarkInfectionModVariables.infectable_blocks.add(Blocks.GOLD_ORE);
		DarkInfectionModVariables.infected_blocks.add(DarkInfectionModBlocks.VOID_STONE_GOLD_ORE.get());
		DarkInfectionModVariables.infectable_blocks.add(Blocks.DEEPSLATE_GOLD_ORE);
		DarkInfectionModVariables.infected_blocks.add(DarkInfectionModBlocks.VOID_STONE_GOLD_ORE.get());
		DarkInfectionModVariables.infectable_blocks.add(Blocks.NETHER_GOLD_ORE);
		DarkInfectionModVariables.infected_blocks.add(DarkInfectionModBlocks.VOID_STONE_GOLD_ORE.get());
		DarkInfectionModVariables.infectable_blocks.add(DarkInfectionModBlocks.DARKDIRT.get());
		DarkInfectionModVariables.infected_blocks.add(DarkInfectionModBlocks.INFECTEDSOIL.get());
		DarkInfectionModVariables.infectable_blocks.add(Blocks.STONE_BRICK_STAIRS);
		DarkInfectionModVariables.infected_blocks.add(DarkInfectionModBlocks.VOID_STONE_BRICK_STAIRS.get());
		DarkInfectionModVariables.infectable_blocks.add(Blocks.DEEPSLATE_BRICK_STAIRS);
		DarkInfectionModVariables.infected_blocks.add(DarkInfectionModBlocks.VOID_STONE_BRICK_STAIRS.get());
		DarkInfectionModVariables.infectable_blocks.add(Blocks.POLISHED_BLACKSTONE_BRICK_STAIRS);
		DarkInfectionModVariables.infected_blocks.add(DarkInfectionModBlocks.VOID_STONE_BRICK_STAIRS.get());
		DarkInfectionModVariables.infectable_blocks.add(Blocks.STONE_BRICK_SLAB);
		DarkInfectionModVariables.infected_blocks.add(DarkInfectionModBlocks.VOID_STONE_BRICK_SLABS.get());
		DarkInfectionModVariables.infectable_blocks.add(Blocks.DEEPSLATE_BRICK_SLAB);
		DarkInfectionModVariables.infected_blocks.add(DarkInfectionModBlocks.VOID_STONE_BRICK_SLABS.get());
		DarkInfectionModVariables.infectable_blocks.add(Blocks.POLISHED_BLACKSTONE_BRICK_SLAB);
		DarkInfectionModVariables.infected_blocks.add(DarkInfectionModBlocks.VOID_STONE_BRICK_SLABS.get());
		DarkInfectionModVariables.infectable_blocks.add(Blocks.POLISHED_BLACKSTONE_BRICK_WALL);
		DarkInfectionModVariables.infected_blocks.add(DarkInfectionModBlocks.VOID_STONE_BRICK_WALLS.get());
		DarkInfectionModVariables.infectable_blocks.add(Blocks.DEEPSLATE_BRICK_WALL);
		DarkInfectionModVariables.infected_blocks.add(DarkInfectionModBlocks.VOID_STONE_BRICK_WALLS.get());
		DarkInfectionModVariables.infectable_blocks.add(Blocks.STONE_BRICK_WALL);
		DarkInfectionModVariables.infected_blocks.add(DarkInfectionModBlocks.VOID_STONE_BRICK_WALLS.get());
		DarkInfectionModVariables.infectable_blocks.add(Blocks.ANCIENT_DEBRIS);
		DarkInfectionModVariables.infected_blocks.add(DarkInfectionModBlocks.DARK_ANCIENT_DEBRIS.get());
		DarkInfectionModVariables.infectable_blocks.add(Blocks.OAK_LOG);
		DarkInfectionModVariables.infected_blocks.add(DarkInfectionModBlocks.DARK_WOOD_LOG.get());
		DarkInfectionModVariables.infectable_blocks.add(Blocks.ACACIA_LOG);
		DarkInfectionModVariables.infected_blocks.add(DarkInfectionModBlocks.DARK_WOOD_LOG.get());
		DarkInfectionModVariables.infectable_blocks.add(Blocks.OAK_PLANKS);
		DarkInfectionModVariables.infected_blocks.add(DarkInfectionModBlocks.DARK_WOOD_PLANKS.get());
		DarkInfectionModVariables.infectable_blocks.add(Blocks.OAK_PLANKS);
		DarkInfectionModVariables.infected_blocks.add(DarkInfectionModBlocks.DARK_WOOD_PLANKS.get());
		DarkInfectionModVariables.infectable_blocks.add(Blocks.SPRUCE_PLANKS);
		DarkInfectionModVariables.infected_blocks.add(DarkInfectionModBlocks.DARK_WOOD_PLANKS.get());
		DarkInfectionModVariables.infectable_blocks.add(Blocks.BIRCH_PLANKS);
		DarkInfectionModVariables.infected_blocks.add(DarkInfectionModBlocks.DARK_WOOD_PLANKS.get());
		DarkInfectionModVariables.infectable_blocks.add(Blocks.JUNGLE_PLANKS);
		DarkInfectionModVariables.infected_blocks.add(DarkInfectionModBlocks.DARK_WOOD_PLANKS.get());
		DarkInfectionModVariables.infectable_blocks.add(Blocks.ACACIA_PLANKS);
		DarkInfectionModVariables.infected_blocks.add(DarkInfectionModBlocks.DARK_WOOD_PLANKS.get());
		DarkInfectionModVariables.infectable_blocks.add(Blocks.DARK_OAK_PLANKS);
		DarkInfectionModVariables.infected_blocks.add(DarkInfectionModBlocks.DARK_WOOD_PLANKS.get());
		DarkInfectionModVariables.infectable_blocks.add(Blocks.CRIMSON_PLANKS);
		DarkInfectionModVariables.infected_blocks.add(DarkInfectionModBlocks.DARK_WOOD_PLANKS.get());
		DarkInfectionModVariables.infectable_blocks.add(Blocks.WARPED_PLANKS);
		DarkInfectionModVariables.infected_blocks.add(DarkInfectionModBlocks.DARK_WOOD_PLANKS.get());
		DarkInfectionModVariables.infectable_blocks.add(Blocks.OAK_LEAVES);
		DarkInfectionModVariables.infected_blocks.add(DarkInfectionModBlocks.DARK_WOOD_LEAVES.get());
		DarkInfectionModVariables.infectable_blocks.add(Blocks.ACACIA_LEAVES);
		DarkInfectionModVariables.infected_blocks.add(DarkInfectionModBlocks.DARK_WOOD_LEAVES.get());
		DarkInfectionModVariables.infectable_blocks.add(Blocks.AZALEA_LEAVES);
		DarkInfectionModVariables.infected_blocks.add(DarkInfectionModBlocks.DARK_WOOD_LEAVES.get());
		DarkInfectionModVariables.infectable_blocks.add(Blocks.FLOWERING_AZALEA_LEAVES);
		DarkInfectionModVariables.infected_blocks.add(DarkInfectionModBlocks.DARK_WOOD_LEAVES.get());
		DarkInfectionModVariables.infectable_blocks.add(Blocks.OAK_WOOD);
		DarkInfectionModVariables.infected_blocks.add(DarkInfectionModBlocks.DARK_WOOD_WOOD.get());
		DarkInfectionModVariables.infectable_blocks.add(Blocks.SPRUCE_WOOD);
		DarkInfectionModVariables.infected_blocks.add(DarkInfectionModBlocks.DARK_WOOD_WOOD.get());
		DarkInfectionModVariables.infectable_blocks.add(Blocks.BIRCH_WOOD);
		DarkInfectionModVariables.infected_blocks.add(DarkInfectionModBlocks.DARK_WOOD_WOOD.get());
		DarkInfectionModVariables.infectable_blocks.add(Blocks.JUNGLE_WOOD);
		DarkInfectionModVariables.infected_blocks.add(DarkInfectionModBlocks.DARK_WOOD_WOOD.get());
		DarkInfectionModVariables.infectable_blocks.add(Blocks.ACACIA_WOOD);
		DarkInfectionModVariables.infected_blocks.add(DarkInfectionModBlocks.DARK_WOOD_WOOD.get());
		DarkInfectionModVariables.infectable_blocks.add(Blocks.DARK_OAK_WOOD);
		DarkInfectionModVariables.infected_blocks.add(DarkInfectionModBlocks.DARK_WOOD_WOOD.get());
		DarkInfectionModVariables.infectable_blocks.add(Blocks.OAK_FENCE);
		DarkInfectionModVariables.infected_blocks.add(DarkInfectionModBlocks.DARK_WOOD_FENCE.get());
		DarkInfectionModVariables.infectable_blocks.add(Blocks.SPRUCE_FENCE);
		DarkInfectionModVariables.infected_blocks.add(DarkInfectionModBlocks.DARK_WOOD_FENCE.get());
		DarkInfectionModVariables.infectable_blocks.add(Blocks.BIRCH_FENCE);
		DarkInfectionModVariables.infected_blocks.add(DarkInfectionModBlocks.DARK_WOOD_FENCE.get());
		DarkInfectionModVariables.infectable_blocks.add(Blocks.JUNGLE_FENCE);
		DarkInfectionModVariables.infected_blocks.add(DarkInfectionModBlocks.DARK_WOOD_FENCE.get());
		DarkInfectionModVariables.infectable_blocks.add(Blocks.CRIMSON_STEM);
		DarkInfectionModVariables.infected_blocks.add(DarkInfectionModBlocks.DARK_WOOD_LOG.get());
		DarkInfectionModVariables.infectable_blocks.add(Blocks.WARPED_STEM);
		DarkInfectionModVariables.infected_blocks.add(DarkInfectionModBlocks.DARK_WOOD_LOG.get());
		DarkInfectionModVariables.infectable_blocks.add(Blocks.WARPED_HYPHAE);
		DarkInfectionModVariables.infected_blocks.add(DarkInfectionModBlocks.DARK_WOOD_WOOD.get());
		DarkInfectionModVariables.infectable_blocks.add(Blocks.CRIMSON_HYPHAE);
		DarkInfectionModVariables.infected_blocks.add(DarkInfectionModBlocks.DARK_WOOD_WOOD.get());
		DarkInfectionModVariables.infectable_blocks.add(Blocks.ACACIA_FENCE);
		DarkInfectionModVariables.infected_blocks.add(DarkInfectionModBlocks.DARK_WOOD_FENCE.get());
		DarkInfectionModVariables.infectable_blocks.add(Blocks.DARK_OAK_FENCE);
		DarkInfectionModVariables.infected_blocks.add(DarkInfectionModBlocks.DARK_WOOD_FENCE.get());
		DarkInfectionModVariables.infectable_blocks.add(Blocks.CRIMSON_FENCE);
		DarkInfectionModVariables.infected_blocks.add(DarkInfectionModBlocks.DARK_WOOD_FENCE.get());
		DarkInfectionModVariables.infectable_blocks.add(Blocks.WARPED_FENCE);
		DarkInfectionModVariables.infected_blocks.add(DarkInfectionModBlocks.DARK_WOOD_FENCE.get());
		DarkInfectionModVariables.infectable_blocks.add(Blocks.OAK_FENCE_GATE);
		DarkInfectionModVariables.infected_blocks.add(DarkInfectionModBlocks.DARK_WOOD_FENCE_GATE.get());
		DarkInfectionModVariables.infectable_blocks.add(Blocks.SPRUCE_FENCE_GATE);
		DarkInfectionModVariables.infected_blocks.add(DarkInfectionModBlocks.DARK_WOOD_FENCE_GATE.get());
		DarkInfectionModVariables.infectable_blocks.add(Blocks.BIRCH_FENCE_GATE);
		DarkInfectionModVariables.infected_blocks.add(DarkInfectionModBlocks.DARK_WOOD_FENCE_GATE.get());
		DarkInfectionModVariables.infectable_blocks.add(Blocks.JUNGLE_FENCE_GATE);
		DarkInfectionModVariables.infected_blocks.add(DarkInfectionModBlocks.DARK_WOOD_FENCE_GATE.get());
		DarkInfectionModVariables.infectable_blocks.add(Blocks.ACACIA_FENCE_GATE);
		DarkInfectionModVariables.infected_blocks.add(DarkInfectionModBlocks.DARK_WOOD_FENCE_GATE.get());
		DarkInfectionModVariables.infectable_blocks.add(Blocks.DARK_OAK_FENCE_GATE);
		DarkInfectionModVariables.infected_blocks.add(DarkInfectionModBlocks.DARK_WOOD_FENCE_GATE.get());
		DarkInfectionModVariables.infectable_blocks.add(Blocks.CRIMSON_FENCE_GATE);
		DarkInfectionModVariables.infected_blocks.add(DarkInfectionModBlocks.DARK_WOOD_FENCE_GATE.get());
		DarkInfectionModVariables.infectable_blocks.add(Blocks.WARPED_FENCE_GATE);
		DarkInfectionModVariables.infected_blocks.add(DarkInfectionModBlocks.DARK_WOOD_FENCE_GATE.get());
		DarkInfectionModVariables.infectable_blocks.add(Blocks.OAK_STAIRS);
		DarkInfectionModVariables.infected_blocks.add(DarkInfectionModBlocks.DARK_WOOD_STAIRS.get());
		DarkInfectionModVariables.infectable_blocks.add(Blocks.SPRUCE_STAIRS);
		DarkInfectionModVariables.infected_blocks.add(DarkInfectionModBlocks.DARK_WOOD_STAIRS.get());
		DarkInfectionModVariables.infectable_blocks.add(Blocks.BIRCH_STAIRS);
		DarkInfectionModVariables.infected_blocks.add(DarkInfectionModBlocks.DARK_WOOD_STAIRS.get());
		DarkInfectionModVariables.infectable_blocks.add(Blocks.JUNGLE_STAIRS);
		DarkInfectionModVariables.infected_blocks.add(DarkInfectionModBlocks.DARK_WOOD_STAIRS.get());
		DarkInfectionModVariables.infectable_blocks.add(Blocks.ACACIA_STAIRS);
		DarkInfectionModVariables.infected_blocks.add(DarkInfectionModBlocks.DARK_WOOD_STAIRS.get());
		DarkInfectionModVariables.infectable_blocks.add(Blocks.DARK_OAK_STAIRS);
		DarkInfectionModVariables.infected_blocks.add(DarkInfectionModBlocks.DARK_WOOD_STAIRS.get());
		DarkInfectionModVariables.infectable_blocks.add(Blocks.CRIMSON_STAIRS);
		DarkInfectionModVariables.infected_blocks.add(DarkInfectionModBlocks.DARK_WOOD_STAIRS.get());
		DarkInfectionModVariables.infectable_blocks.add(Blocks.WARPED_STAIRS);
		DarkInfectionModVariables.infected_blocks.add(DarkInfectionModBlocks.DARK_WOOD_STAIRS.get());
	}
}
